export const products = [
    {
        id: 1,
        name: 'Nike Dunk Low',
        url: 'https://i.pinimg.com/564x/e5/78/57/e5785727e972ff54111d0a15fd93d694.jpg',
        type: 'Men',
        bestseller: true,
        tag: 'Summit White/Wolf Grey/Light Carbon',
        size: '37.5',
        price: 1000,
        sale: 0,
        colour: [
            { nameCol: 'Black', codingCol: '#000000' },
            { nameCol: 'Red', codingCol: '#ff0000' },
            { nameCol: 'Orange', codingCol: '#ffa500' },
            { nameCol: 'Blue', codingCol: '#0000ff' },
            { nameCol: 'White', codingCol: '#fffff' },
            { nameCol: 'Green', codingCol: '#008000' },
            { nameCol: 'Yellow', codingCol: '#ffff00' },
            { nameCol: 'Gray', codingCol: '#808080' },
            { nameCol: 'Pink', codingCol: '#ffc0cb' },
        ],
        quantity: 1,
    },
    {
        id: 2,
        name: 'Nike Dunk Low',
        url: 'https://i.pinimg.com/564x/eb/3e/85/eb3e854c84d45e737fec59b34ca2d42d.jpg',
        type: 'Men',
        tag: 'Summit White/Wolf Grey/Light Carbon',
        size: '37.5',
        price: 1000,
        sale: 0,
        colour: [
            { nameCol: 'Black', codingCol: '#000000' },
            { nameCol: 'Red', codingCol: '#ff0000' },
            { nameCol: 'Orange', codingCol: '#ffa500' },
            { nameCol: 'Blue', codingCol: '#0000ff' },
            { nameCol: 'Yellow', codingCol: '#ffff00' },
            { nameCol: 'Gray', codingCol: '#808080' },
            { nameCol: 'Pink', codingCol: '#ffc0cb' },
        ],
        quantity: 1,
    },
    {
        id: 3,
        name: 'Nike Dunk Low',
        url: 'https://i.pinimg.com/564x/be/ea/1c/beea1cc36331159eef2b2f29f03633c1.jpg',
        type: 'Men',
        tag: 'Summit White/Wolf Grey/Light Carbon',
        size: '37.5',
        price: 1000,
        sale: 0,
        colour: [
            { nameCol: 'Black', codingCol: '#000000' },
            { nameCol: 'Red', codingCol: '#ff0000' },
            { nameCol: 'Orange', codingCol: '#ffa500' },
            { nameCol: 'Blue', codingCol: '#0000ff' },
            { nameCol: 'White', codingCol: '#fffff' },
            { nameCol: 'Green', codingCol: '#008000' },
            { nameCol: 'Yellow', codingCol: '#ffff00' },
            { nameCol: 'Gray', codingCol: '#808080' },
            { nameCol: 'Pink', codingCol: '#ffc0cb' },
        ],
        quantity: 1,
    },
    {
        id: 4,
        name: 'Nike Dunk Low',
        url: 'https://i.pinimg.com/564x/c3/22/32/c322326c567d06efeb5269538308ae72.jpg',
        type: 'Men',
        tag: 'Summit White/Wolf Grey/Light Carbon',
        size: '37.5',
        price: 4325,
        sale: 40,
        colour: [
            { nameCol: 'Black', codingCol: '#000000' },
            { nameCol: 'Red', codingCol: '#ff0000' },
            { nameCol: 'Orange', codingCol: '#ffa500' },
            { nameCol: 'Blue', codingCol: '#0000ff' },
            { nameCol: 'Green', codingCol: '#008000' },
            { nameCol: 'Yellow', codingCol: '#ffff00' },
            { nameCol: 'Gray', codingCol: '#808080' },
            { nameCol: 'Pink', codingCol: '#ffc0cb' },
        ],
        quantity: 1,
    },
    {
        id: 5,
        name: 'Nike Dunk Low',
        url: 'https://i.pinimg.com/564x/84/a1/2b/84a12b9c003fc0eba64332041fa5d138.jpg',
        type: 'Men',
        tag: 'Summit White/Wolf Grey/Light Carbon',
        size: '37.5',
        price: 1000,
        sale: 40,
        colour: [
            { nameCol: 'Black', codingCol: '#000000' },
            { nameCol: 'Red', codingCol: '#ff0000' },
            { nameCol: 'Orange', codingCol: '#ffa500' },
            { nameCol: 'Blue', codingCol: '#0000ff' },
            { nameCol: 'White', codingCol: '#fffff' },
            { nameCol: 'Green', codingCol: '#008000' },
            { nameCol: 'Yellow', codingCol: '#ffff00' },
            { nameCol: 'Gray', codingCol: '#808080' },
            { nameCol: 'Pink', codingCol: '#ffc0cb' },
        ],
        quantity: 1,
    },
    {
        id: 6,
        name: 'Nike Dunk Low',
        url: 'https://i.pinimg.com/564x/10/a4/8e/10a48e03ce3a5aad472257761aaa22c5.jpg',
        type: 'Men',
        tag: 'Summit White/Wolf Grey/Light Carbon',
        size: '37.5',
        price: 1000,
        sale: 40,
        colour: [
            { nameCol: 'Black', codingCol: '#000000' },
            { nameCol: 'Red', codingCol: '#ff0000' },
            { nameCol: 'Orange', codingCol: '#ffa500' },
            { nameCol: 'Yellow', codingCol: '#ffff00' },
            { nameCol: 'Gray', codingCol: '#808080' },
            { nameCol: 'Pink', codingCol: '#ffc0cb' },
        ],
        quantity: 1,
    },
    {
        id: 7,
        name: 'Nike Dunk Low',
        url: 'https://i.pinimg.com/564x/eb/3e/85/eb3e854c84d45e737fec59b34ca2d42d.jpg',
        type: 'Men',
        tag: 'Summit White/Wolf Grey/Light Carbon',
        size: '37.5',
        price: 999,
        sale: 40,
        colour: [
            { nameCol: 'Black', codingCol: '#000000' },
            { nameCol: 'Red', codingCol: '#ff0000' },
            { nameCol: 'Orange', codingCol: '#ffa500' },
            { nameCol: 'Blue', codingCol: '#0000ff' },
            { nameCol: 'White', codingCol: '#fffff' },
            { nameCol: 'Green', codingCol: '#008000' },
            { nameCol: 'Yellow', codingCol: '#ffff00' },
            { nameCol: 'Gray', codingCol: '#808080' },
            { nameCol: 'Pink', codingCol: '#ffc0cb' },
        ],
        quantity: 1,
    },
    {
        id: 8,
        name: 'Nike Dunk Low',
        url: 'https://i.pinimg.com/564x/be/ea/1c/beea1cc36331159eef2b2f29f03633c1.jpg',
        type: 'Men',
        tag: 'Summit White/Wolf Grey/Light Carbon',
        size: '37.5',
        price: 1000,
        sale: 40,
        colour: [
            { nameCol: 'Black', codingCol: '#000000' },
            { nameCol: 'Red', codingCol: '#ff0000' },
            { nameCol: 'Orange', codingCol: '#ffa500' },
            { nameCol: 'Blue', codingCol: '#0000ff' },
            { nameCol: 'White', codingCol: '#fffff' },
            { nameCol: 'Green', codingCol: '#008000' },
            { nameCol: 'Yellow', codingCol: '#ffff00' },
        ],
        quantity: 1,
    },
    {
        id: 9,
        name: 'Nike Dunk Low',
        url: 'https://i.pinimg.com/564x/66/ca/8c/66ca8cccf0f7c79f37ba2496eddd5f6c.jpg',
        type: 'Men',
        tag: 'Summit White/Wolf Grey/Light Carbon',
        size: '37.5',
        price: 1000,
        sale: 40,
        colour: [
            { nameCol: 'Black', codingCol: '#000000' },
            { nameCol: 'Red', codingCol: '#ff0000' },
            { nameCol: 'White', codingCol: '#fffff' },
            { nameCol: 'Green', codingCol: '#008000' },
            { nameCol: 'Yellow', codingCol: '#ffff00' },
            { nameCol: 'Gray', codingCol: '#808080' },
            { nameCol: 'Pink', codingCol: '#ffc0cb' },
        ],
        quantity: 1,
    },
    {
        id: 10,
        name: 'Nike Dunk Low',
        url: 'https://i.pinimg.com/564x/10/a4/8e/10a48e03ce3a5aad472257761aaa22c5.jpg',
        type: 'Men',
        tag: 'Summit White/Wolf Grey/Light Carbon',
        size: '37.5',
        price: 1000,
        sale: 40,
        colour: [
            { nameCol: 'Black', codingCol: '#000000' },
            { nameCol: 'Red', codingCol: '#ff0000' },
            { nameCol: 'Blue', codingCol: '#0000ff' },
            { nameCol: 'White', codingCol: '#fffff' },
            { nameCol: 'Green', codingCol: '#008000' },
            { nameCol: 'Yellow', codingCol: '#ffff00' },
            { nameCol: 'Gray', codingCol: '#808080' },
            { nameCol: 'Pink', codingCol: '#ffc0cb' },
        ],
        quantity: 1,
    },
];
